### ISSUE TITLE
Confused with PyProCar version and documentation

### ISSUE THREAD

**Issue by alpinnovianus** [romerogroup/pyprocar#108]
Hello PyProCar team,

I'm a little confused with which version PyProCar is currently on.

Changelog in GitHub shows 5.6.4.
Releases page in GitHub shows 5.6.3 is latest.
PyPI shows 5.6.6 (https://pypi.org/project/PyProcar/5.6.6/)
and documentation page is 2.0.0 (https://romerogroup.github.io/pyprocar/)

I myself remember I used v5.6.5 before, with documentation page also written in that version.
But now this version disappears from GitHub or the documentation page completely.

Am I missing an announcement or something?

**Comment by lllangWV** [comment]
Hey alpinnovianus,

Sorry for the confusion. We were in the process of updating the packaging and had discrepancies between pypi, github, and the docs

Changelog is now -> v6.0.0
Releases page in GitHub is now -> v6.0.0
PyPI -> 6.0.0 (https://pypi.org/project/PyProcar/6.0.0/)
Documentation page -> 6.0.0

Thank you for pointing this out!

Logan Lang

**Comment by phyjagjit** [comment]
Even I am facing the same problem. The documentation works fine with version 5.6.4. But, after updating to 6.0.0 version, the codes according to the documentation arent working.

**Comment by alpinnovianus** [comment]
> Hey alpinnovianus,
> 
> Sorry for the confusion. We were in the process of updating the packaging and had discrepancies between pypi, github, and the docs
> 
> Changelog is now -> v6.0.0 Releases page in GitHub is now -> v6.0.0 PyPI -> 6.0.0 (https://pypi.org/project/PyProcar/6.0.0/) Documentation page -> 6.0.0
> 
> Thank you for pointing this out!
> 
> Logan Lang

Dear Logan,

I think it is necessary to add in GitHub Changelog and GitHub releases also the versions 5.6.4 and 5.6.5 to align with PyPI release history page. Currently they're absent in Github release/changelog and hence there's a strange skip from 5.6.3 release to 6.0.0.

In general, I think it should be a rule to have all versions documented in github changelog and releases page even if there's a rollback (actually, it's even more important in that case) or a major update such as going to 6.0.0.
After all, those versions were publicly released and some people might have used them already.
If they just disappear without a trace, it will be worrying for users.

> Even I am facing the same problem. The documentation works fine with version 5.6.4. But, after updating to 6.0.0 version, the codes according to the documentation arent working.

@phyjagjit, I think Logan might have simply changed the title from 2.0.0 in that page to 6.0.0.
If I look at the copyright year at the bottom of the page, I am afraid this documentation page might also be an old page instead of a new one (i.e., maybe it was actually made for version 2.0.0 and not compatible with 6.0.0).

> © Copyright 2020, Romero Group.
> Built with the [PyData Sphinx Theme ](https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html)0.12.0.
> 
> Created using [Sphinx](http://sphinx-doc.org/) 5.3.0.

**Comment by phyjagjit** [comment]
@alpinnovianus I think that is the case. And it seems a lot of things have changed in the new verion. It doesnot identify the outcar file as it used to and hence it shows error.

**Comment by lllangWV** [comment]
@alpinnovianus Thank you for the suggestion, you are absolutely right. I will add versions 5.6.4 and 5.6.5 to the GitHub Changelog and GitHub releases. Sorry for the confusion, we were in the process of making major code base and documentation changes and forgot the update the changelog and releases. I talked with another developer, who suggested we host the old documentation for versions <5.6.5 for people who want to use the old versions. I will add the link to this documentation in the README.md. I will also make a note in the README.md about the changes that have occurred to make the users more aware of them. I can not make these changes today but will do them tomorrow.

@phyjagjit That is the case. In the most recent version, we removed the ability to specify the OUTCAR in favor of specifying the directory with the keyword argument 'dirname' containing all the files you would expect. If you liked to be able to specify the OUTCAR, PROCAR, and POSCAR we can add those keyword arguments back in.

If there are any other issues please tell us and we will address them as quickly as we can.

Logan Lang

**Comment by shilendraS786** [comment]
Dear  Developer lllangWV,

After PyProcar upgrading to v6.5.0, I am plotting spin texture it is showing Wyckoff error (while same calculation I have plotted with old version). I wanted to plot with new version since I want good quality axes legend etc (plotting with older version it does not show good quality). How can I resolve this wyckoffserror. Besides how can I improve legends fonts, axes labels etc in older version. The error is following:

Parsing KPOINTS file: /home/shilendra/Downloads/ClSbSe/As_doped/spin_texture/KPOINTS
Traceback (most recent call last):
  File "/home/shilendra/Downloads/ClSbSe/As_doped/spin_texture/plot_rashba_spin_spliting.py", line 14, in <module>
    pyprocar.fermi2D(code = 'vasp',
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/scripts/scriptFermi2D.py", line 168, in fermi2D
    parser = io.Parser(code=code, dirpath=dirname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/io/parser.py", line 30, in __init__
    self._parse()
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/io/parser.py", line 53, in _parse
    self._parse_vasp()
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/io/parser.py", line 247, in _parse_vasp
    self.structure = parser.structure
                     ^^^^^^^^^^^^^^^^
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/io/vasp.py", line 2166, in structure
    return Structure(
           ^^^^^^^^^^
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/core/structure.py", line 79, in __init__
    self.get_wyckoff_positions()
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/core/structure.py", line 367, in get_wyckoff_positions
    spglib.get_symmetry_dataset(self._spglib_cell, symprec).wyckoffs
AttributeError: 'dict' object has no attribute 'wyckoffs'

**Comment by shilendraS786** [comment]
Dear@lllangWV ,

According your suggestions I installed (pip install --pre pyprocar) version 6.5.1.dev8.
Now previous error of Wyckoffs has disappeared but new error occurred (still it is not plotting spin texture of my system). The error message is following:

Parsing KPOINTS file: /home/shilendra/Downloads/ClSbSe/As_doped/spin_texture/KPOINTS
Traceback (most recent call last):
  File "/home/shilendra/Downloads/ClSbSe/As_doped/spin_texture/plot_rashba_spin_spliting.py", line 14, in <module>
    pyprocar.fermi2D(
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/scripts/scriptFermi2D.py", line 168, in fermi2D
    parser = io.Parser(code=code, dirpath=dirname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/io/parser.py", line 30, in __init__
    self._parse()
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/io/parser.py", line 53, in _parse
    self._parse_vasp()
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/io/parser.py", line 247, in _parse_vasp
    self.structure = parser.structure
                     ^^^^^^^^^^^^^^^^
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/io/vasp.py", line 2185, in structure
    return Structure(
           ^^^^^^^^^^
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/core/structure.py", line 53, in __init__
    fractional_coordinates = fractional_coordinates or []
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


I am using below script to plot spin texture:


# importing pyprocar and specifying local data_dir
import os
import pyprocar

DATA_DIR = "/home/shilendra/Downloads/ClSbSe/As_doped/spin_texture"

###############################################################################
pyprocar.fermi2D(
    code="vasp",
    dirname=DATA_DIR,
    energy=1.2,
    spin_texture=True,
    no_arrow=True,
    spin_projection="x",
    plot_color_bar=True,
)
###############################################################################

Regards
Shilendra

**Comment by lllangWV** [comment]
Hey, 

the tests I created only covered when the input was list, this would fail on numpy arrays. It should have been
```python

atoms = atoms if atoms is not None else []
fractional_coordinates = fractional_coordinates if fractional_coordinates is not None else []
cartesian_coordinates = cartesian_coordinates if cartesian_coordinates is not None else []
rotations = rotations if rotations is not None else []
```

I have made the changes. Just do the same install. 

Hopefully, this time it is alright. Here is the example I just ran

```python
pyprocar.fermi2D(
    code="vasp",
    dirname=calc_dirs["mesh"]["non_colinear"],
    spin_texture=True,
    fermi= fermi_dict["non_colinear"],
    atoms=[1],
    spin_projection="x",
    cmap="seismic",
    orbitals=[4, 5, 6, 7, 8],
    k_z_plane_tol=0.01,
    linewidth=1,
    plot_color_bar=True,
    arrow_density=5,
    arrow_size=0.5,
    contour_alpha=0.0,
    clim=[-0.5, 0.5],
    dpi=300,
    use_cache=False,
)
```



<img width="661" height="535" alt="Image" src="https://github.com/user-attachments/assets/9645e296-d408-4793-b5e4-41f86bff5ece" />

**Comment by lllangWV** [comment]
Sorry, give it 5 minutes. The updates need to deploy.

**Comment by shilendraS786** [comment]
Dear@lllangWV,

Still following error is occurring with new version 6.5.1.dev1. 
 But I have plotted same spin texture with previous version 6.1.7 installed in my another system. I have attached here folder of my spin texture calculations (plotting script is also inside folder). I will try to manage with previous version but I am unable to increase tick and label (Sx Projection) of heat map scale for clear and good looking for image publication in journal (please see attached spin texture figure). Can you please tell me how can I modify my script to increase heat map label (Sx projection) and its associated tick labels). 

With new version error is following:

Parsing KPOINTS file: /home/shilendra/Downloads/spin_texture/ClAsSb/2spin_texture/KPOINTS
Traceback (most recent call last):
  File "/home/shilendra/Downloads/spin_texture/ClAsSb/2spin_texture/plot_rashba_spin_spliting.py", line 19, in <module>
    pyprocar.fermi2D(code = 'vasp',
  File "/home/shilendra/anaconda3/lib/python3.11/site-packages/pyprocar/scripts/scriptFermi2D.py", line 174, in fermi2D
    f"Detected symmetry operations ({structure.rotations.shape}). Applying to ebs to get full BZ"
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'shape'




<img width="1440" height="864" alt="Image" src="https://github.com/user-attachments/assets/1be103da-7eec-4e11-bbb1-34fdaca2ea1f" />

[2spin_texture.zip](https://github.com/user-attachments/files/21201705/2spin_texture.zip)


Regards
Shilendra

**Comment by shilendraS786** [comment]
Version 6.5.1.dev11 created on Mar 6th, 2025
(This latest version I installed).

**Comment by lllangWV** [comment]
Hey @shilendraS786,

Thanks for reaching out and providing the detailed report. Apologies for the delay and the issues you've encountered. I've been transitioning between code versions, and your feedback is very helpful.

## Bug Fix: `AttributeError`

I just pushed changes to address `AttributeError: 'list' object has no attribute 'shape'` and I made some changes to `fermi2d` to allow for more customization for the plot axes.

Install them with

```python
pip uninstall pyprocar
pip install --pre pyprocar
```

## Plot Customization for Publication
To address your second question, I've added several `*_kwargs` parameters to the `fermi2D` function. This will give you the fine-grained control you need to create publication-quality figures.

Specifically, you can now use:
- `colorbar_label_kwargs` to customize the colorbar title (your 'Sx Projection' label).
- `colorbar_tick_params_kwargs` to customize the colorbar tick labels.

These parameters accept a dictionary of keyword arguments that are passed directly to the underlying Matplotlib functions (set_ylabel and tick_params, respectively), allowing you to easily adjust font size, weight, color, and more.

If you need more control over the texture arrows use `plot_arrows_kwargs`, which are arguments for the [matplotlib.quiver](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html) function.

```python
labelsize = 20
pyprocar.fermi2D(code = 'vasp',
                dirname=CURRENT_DIR,
                mode="spin_texture",
                energy = -0.4,
                spin_projection='x',
                # band_indices=[[19,20,21,22,23], []],
                # band_indices=[[23], []],
                arrow_scale=0.5,
                linewidth=0.2,
                linestyle='dashed',
                point_density=15,
                show_colorbar=True,
                plot_arrows=True,
                plot_scatter=False,
                plot_contours=True,
                dpi="figure",
                clim=(-0.5, 0.5),
                xlabel_kwargs={"xlabel": "$k_{x}$  ($\\AA^{-1}$)", "fontsize": labelsize, "fontweight": "bold", "color": "blue"},
                ylabel_kwargs={"ylabel": "$k_{y}$  ($\\AA^{-1}$)", "fontsize": labelsize, "fontweight": "bold", "color": "blue"},
                tick_params_kwargs={"axis": "both", "which": "major", "reset": True, "labelsize": labelsize},
                colorbar_tick_kwargs={"n_ticks": 5},
                colorbar_tick_params_kwargs={"labelsize": labelsize},
                colorbar_label_kwargs={"fontsize": 32},
                )

```


<img width="1677" height="903" alt="Image" src="https://github.com/user-attachments/assets/22ca18bd-8c97-442b-a91d-edefd4dcaff4" />


## Future Development
Just as a heads-up, we are planning to move away from a single, large plotting function in favor of an object-oriented interface. This change will provide more flexibility for customizing plots in the future.

Let me know if the update works for you!


Logan Lang

**Comment by lllangWV** [comment]
Was this with the same exact data? 

What version of `matplotlib` are you using? In version 3.8, they changed the ContourSet to inherit directly from collections which has the attribute `get_paths`. My guess is you are using an older version of matplotlib. 

I have updated the dependency requirements of pyprocar ensure `"matplotlib>=3.8"`. Previously, we did not demand this.

**Comment by lllangWV** [comment]
Great!

> Every thing is fine but little elongated image rather than spherical (compared to which I plotted from old_version).

This was my bad, I removed the setting of the aspect ratio when I was making changes I added it back. Download the changes with 

```python
pip uninstall pyprocar
pip install --pre pyprocar
```


> Please also tell which command we can change heat map color (if some one wants to change heat map color blue and red or any other)

The command is `cmap`. I would suggest using a diverging color map like `cmap="coolwarm"`,  `cmap="bwr"`, or `cmap="seismic"`.` Other colormaps are found [here](https://matplotlib.org/stable/users/explain/colors/colormaps.html). Make sure to install the new changes first as specified above.




<img width="1626" height="1193" alt="Image" src="https://github.com/user-attachments/assets/b2b38b29-2a04-431f-a1fb-98339ec45110" />

```python
labelsize = 20
pyprocar.fermi2D(code = 'vasp',
                dirname=CURRENT_DIR,
                mode="spin_texture",
                fermi = -3.3521 ,
                energy = -0.4,
                spin_projection='x',
                # band_indices=[[19,20,21,22,23], []],
                # band_indices=[[23], []],
                arrow_scale=0.5,
                linewidth=0.2,
                linestyle='dashed',
                point_density=15,
                show_colorbar=True,
                plot_arrows=True,
                plot_scatter=False,
                plot_contours=True,
                cmap="seismic",
                dpi="figure",
                clim=(-0.5, 0.5),
                xlabel_kwargs={"xlabel": "$k_{x}$  ($\\AA^{-1}$)", "fontsize": labelsize, "fontweight": "bold", "color": "blue"},
                ylabel_kwargs={"ylabel": "$k_{y}$  ($\\AA^{-1}$)", "fontsize": labelsize, "fontweight": "bold", "color": "blue"},
                # xlim_kwargs={"xlimits": (-0.5, 0.5)},
                # ylim_kwargs={"ylimits": (-0.5, 0.5)},
                tick_params_kwargs={"axis": "both", "which": "major", "reset": True, "labelsize": labelsize},
                colorbar_tick_kwargs={"n_ticks": 5},
                colorbar_tick_params_kwargs={"labelsize": labelsize},
                colorbar_label_kwargs={"fontsize": 32},
                )


```

I'm glad I could help! 

Logan Lang

**Comment by shilendraS786** [comment]
Dear@lllangWV,

Very much thank you for your consistent efforts and time.

Nice quality, informative and very good looking spin texture images by PyProcar. I also reproduced same spin texture images for Sx, Sy and Sz projections.


Regards
Shilendra

<img width="1253" height="867" alt="Image" src="https://github.com/user-attachments/assets/ef611989-4337-48ed-86ed-bc3f8b777559" />

<img width="1246" height="870" alt="Image" src="https://github.com/user-attachments/assets/85a28af7-b3e4-426f-9ef4-53327a27154d" />
