### ISSUE TITLE
TypeError: bandsplot() missing 1 required positional argument: 'dirname'

### ISSUE THREAD

**Issue by kaiqi-wang** [romerogroup/pyprocar#129]
Dear all,

I meet a problem when I use pyprocar. Anyone can help me ?

Traceback (most recent call last):
  File "/fs2/home/software/miniconda3/bin/procar.py", line 809, in <module>
    args.func(args)
  File "/fs2/home/software/miniconda3/bin/procar.py", line 23, in call_bandsplot
    pyprocar.bandsplot(
TypeError: bandsplot() missing 1 required positional argument: 'dirname'

**Comment by ahromero** [comment]
You need to provide enough information, this is not enough to check what the problem is. Please describe line by line what you are doing and what you are trying to accomplish.

______________________________________::::__________________________________________
Prof. Aldo Humberto Romero
Director Research Computing, West Virginia University
Eberly Family Distinguished Professor
Fellow American Physical Society
Editor Physica B, Assistant Editor EPJB, Editor Frontiers in Physics
Section Editor Papers in Physics
Member of the Editorial Board of  “Materials” and “Symmetry Physics”

Physics and Astronomy Department
West Virginia University
135 Willey Street, PO Box 6315
111 White Hall
Morgantown, WV 26506
Phone:  304-293-6317
Fax:  304-293-5732
email: ***@***.***


From: 王凯齐 ***@***.***>
Date: Friday, September 1, 2023 at 11:29 PM
To: romerogroup/pyprocar ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [romerogroup/pyprocar] TypeError: bandsplot() missing 1 required positional argument: 'dirname' (Issue #129)

Dear all,

I meet a problem when I use pyprocar. Anyone can help me ?

Traceback (most recent call last):
File "/fs2/home/software/miniconda3/bin/procar.py", line 809, in
args.func(args)
File "/fs2/home/software/miniconda3/bin/procar.py", line 23, in call_bandsplot
pyprocar.bandsplot(
TypeError: bandsplot() missing 1 required positional argument: 'dirname'

―

**Comment by lllangWV** [comment]
Hey kaiqi-wang!

This issue is happening because we have updated bandsplot.py. I need to update scripts/procar.py to reflect these changes.

In the meantime, you can either create a python script and use the updated bandsplot function, or you can use an older version of pyprocar==5.6.6. You install this version through pip or go to the github releases.

Tell me if these solutions are satisfactory for you. If you have any other questions, please let us know!

**Comment by kaiqi-wang** [comment]
> Hey kaiqi-wang!
> 
> This issue is happening because we have updated bandsplot.py. I need to update scripts/procar.py to reflect these changes.
> 
> In the meantime, you can either create a python script and use the updated bandsplot function, or you can use an older version of pyprocar==5.6.6. You install this version through pip or go to the github releases.
> 
> Tell me if these solutions are satisfactory for you. If you have any other questions, please let us know!

Thank you very much. I already know the reason and hope other users can pay attention. In versions before v6.0.0, the dirname parameter defaults to the folder where OUTCAR and PROCAR are located, but after this, it is necessary to specify the specific folder. I am using a bash script that does not support the parameter dirname when using pyprocar. （I mean in that way）. I have changed the instructions for installing the script on the official website to a Python script and it can be run. Like this:

**#!/usr/bin/env python

import pyprocar

pyprocar.bandsplot(
	code='vasp', \
	_dirname='./', \_       # Pay attention here
	elimit=[-2,2], \
	mode='plain', \
	color='blue', \
	savefig='band.png')**
