### ISSUE TITLE
ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad'

### ISSUE THREAD

**Issue by ChenqiangHua** [romerogroup/pyprocar#30]
May i ask one quesion?  Is it the bug or just my PC's problem?
First I installed conda and then I used "pip3 install pyprocar", and it successfully installed.
(if i type this command again it will show me that "Requirement already satisfied: pyprocar in /home/atk6/anaconda3/lib/python3.7/site-packages (5.2.0)")
But when i import pyprocar  , error happens:

"ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (/home/atk6/anaconda3/lib/python3.7/site-packages/numpy/lib/arraypad.py)"

I am really confused about this error since i successfullt tested pyprocar once several months ago.
Can anyone hep me ?

**Comment by ChenqiangHua** [comment]
>>> import pyprocar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/atk6/anaconda3/lib/python3.7/site-packages/pyprocar/__init__.py", line 37, in <module>
    import skimage
  File "/home/atk6/anaconda3/lib/python3.7/site-packages/skimage/__init__.py", line 157, in <module>
    from .util.dtype import *
  File "/home/atk6/anaconda3/lib/python3.7/site-packages/skimage/util/__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "/home/atk6/anaconda3/lib/python3.7/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (/home/atk6/anaconda3/lib/python3.7/site-packages/numpy/lib/arraypad.py)

**Comment by uthpalaherath** [comment]
Hello, 

Can you upgrade skimage and/or numpy and try again please?

Thanks, 

Best,
Uthpala

**Comment by nisel** [comment]
I have the same question. Could you please tell me how to haddle this?

**Comment by uthpalaherath** [comment]
I think this has something to do with your python setup. 
Also, which version of PyProcar are you using?
