### ISSUE TITLE
2D-spin mesh plot,could not convert string to float happen

### ISSUE THREAD

**Issue by ChenqiangHua** [romerogroup/pyprocar#81]
I have run the "pyprocar.fermi2D('PROCAR-repaired', outcar='OUTCAR', st=True, energy=0.01, noarrow=False, spin=3, code='vasp')"
The procar is repaired before fermi2D.            

then after several mins  error happens:
**Traceback (most recent call last):
  File "/beegfs/home/b00004/calculation-hcq/soc/2Dslice/soc/slice/py", line 4, in <module>
    pyprocar.fermi2D('PROCAR-repaired', outcar='OUTCAR', st=True, energy=0.01, noarrow=False, spin=3, code='vasp')
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/pyprocar/scriptFermi2D.py", line 92, in fermi2D
    rec_basis = outcarparser.RecLatOutcar(outcar)
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/pyprocar/utilsprocar/utilsprocar.py", line 271, in RecLatOutcar
    recLat = np.array(recLat, dtype=float)
ValueError: could not convert string to float: '0.000000000171.062194824'**

PS.  my vasp running is successful but PROCAR is large due to 200 atoms.

Can anyone help me?

**Comment by ChenqiangHua** [comment]
my pyprocar version is 5.6.6

**Comment by ChenqiangHua** [comment]
oh my god! I find the origin of this error!  THX for this software!
